# Generated by Django 2.1.7 on 2019-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('whatday', models.CharField(max_length=30, verbose_name='星期几')),
                ('detaltime', models.CharField(max_length=30, verbose_name='上课节次')),
                ('beginfinsh', models.CharField(max_length=30, verbose_name='起始周')),
                ('lessonsname', models.CharField(max_length=256, verbose_name='课程名称')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('place', models.CharField(max_length=128, verbose_name='上课地点')),
                ('comprise', models.CharField(max_length=128, verbose_name='教学班组成')),
                ('lessonsmargin', models.IntegerField(verbose_name='余量')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='pjhz',
            fields=[
                ('id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('xname1', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade1', models.FloatField(verbose_name='评分')),
                ('xname2', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade2', models.FloatField(verbose_name='评分')),
                ('xname3', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade3', models.FloatField(verbose_name='评分')),
                ('xname4', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade4', models.FloatField(verbose_name='评分')),
                ('xname5', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade5', models.FloatField(verbose_name='评分')),
                ('xname6', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade6', models.FloatField(verbose_name='评分')),
                ('xname7', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade7', models.FloatField(verbose_name='评分')),
                ('xname8', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade8', models.FloatField(verbose_name='评分')),
                ('xname9', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade9', models.FloatField(verbose_name='评分')),
                ('xname10', models.CharField(max_length=30, verbose_name='听课老师')),
                ('grade10', models.FloatField(verbose_name='评分')),
            ],
            options={
                'verbose_name': '评价汇总表',
                'verbose_name_plural': '评价汇总表',
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='pjjl',
            fields=[
                ('id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('lessonsname', models.CharField(max_length=256, verbose_name='课程名称')),
                ('xname', models.CharField(max_length=30, verbose_name='听课老师')),
                ('item1', models.IntegerField(verbose_name='标准1')),
                ('item2', models.IntegerField(verbose_name='标准2')),
                ('item3', models.IntegerField(verbose_name='标准3')),
                ('item4', models.IntegerField(verbose_name='标准4')),
                ('item5', models.IntegerField(verbose_name='标准5')),
                ('item6', models.IntegerField(verbose_name='标准6')),
                ('item7', models.IntegerField(verbose_name='标准7')),
                ('item8', models.IntegerField(verbose_name='标准8')),
                ('item9', models.IntegerField(verbose_name='标准9')),
                ('item10', models.IntegerField(verbose_name='标准10')),
                ('item11', models.IntegerField(verbose_name='标准11')),
                ('item12', models.IntegerField(verbose_name='标准12')),
                ('item13', models.IntegerField(verbose_name='标准13')),
                ('item14', models.IntegerField(verbose_name='标准14')),
            ],
            options={
                'verbose_name': '评价记录表',
                'verbose_name_plural': '评价记录表',
                'db_table': 'evaluation_records',
            },
        ),
        migrations.CreateModel(
            name='reserved',
            fields=[
                ('id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('xid', models.CharField(max_length=30, verbose_name='选课人工号')),
                ('xname', models.CharField(max_length=30, verbose_name='选课人')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('lessonsname', models.CharField(max_length=256, verbose_name='课程名称')),
                ('whatday', models.CharField(max_length=30, verbose_name='星期几')),
                ('detaltime', models.CharField(max_length=30, verbose_name='上课节次')),
                ('whichweek', models.CharField(max_length=30, verbose_name='起始周')),
                ('place', models.CharField(max_length=128, verbose_name='上课地点')),
                ('comprise', models.CharField(max_length=128, verbose_name='教学班组成')),
                ('mark', models.BooleanField(verbose_name='是否已评价')),
            ],
            options={
                'verbose_name': '选课单',
                'verbose_name_plural': '选课单',
                'db_table': 'reserved',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
